server:
  port: 8080

spring:
  profiles:
    active: dev
  rabbitmq:
    host: 43.138.194.150
    port: 5672
    username: config
    password: config
    virtual-host: /config

management:
  endpoints:
    web:
      exposure:
        include: "*"
