server:
  port: 8080

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: config
    password: config
    virtual-host: /config

management:
  endpoints:
    web:
      exposure:
        include: "*"
